/**
 * Einheiten aus knx_master.xml auf QUDT. Jeder Eintrag ist gegen das
 * QUDT-Einheitenvokabular geprueft (qudt.org/vocab/unit, Stand 2026-10-08).
 * Was QUDT nicht kennt oder keine Einheit ist ("fan stage", "l/m²", "Month"),
 * bekommt bewusst kein `unit`, statt etwas Falsches zu behaupten.
 */

export const QUDT_UNIT_NAMESPACE = "http://qudt.org/vocab/unit/";

const KNX_TO_QUDT: Readonly<Record<string, string>> = {
  "%": "PERCENT",
  ms: "MilliSEC",
  s: "SEC",
  seconds: "SEC",
  min: "MIN",
  minutes: "MIN",
  h: "HR",
  hours: "HR",
  "°C": "DEG_C",
  "temperature (°C)": "DEG_C",
  "°F": "DEG_F",
  K: "K",
  "temperature (K)": "K",
  "K/h": "K-PER-HR",
  "°": "DEG",
  rad: "RAD",
  "rad/s": "RAD-PER-SEC",
  "rad/s²": "RAD-PER-SEC2",
  pulses: "NUM",
  "counter pulses": "NUM",
  Pa: "PA",
  "m³/h": "M3-PER-HR",
  "m³/s": "M3-PER-SEC",
  "m³": "M3",
  "m²": "M2",
  l: "L",
  "l/h": "L-PER-HR",
  m: "M",
  mm: "MilliM",
  "m/s": "M-PER-SEC",
  "m/s²": "M-PER-SEC2",
  "km/h": "KiloM-PER-HR",
  lux: "LUX",
  Lux: "LUX",
  lm: "LM",
  cd: "CD",
  "cd/m²": "CD-PER-M2",
  sr: "SR",
  ppm: "PPM",
  "g/m³": "GM-PER-M3",
  "µg/m³": "MicroGM-PER-M3",
  "kg/m³": "KiloGM-PER-M3",
  kg: "KiloGM",
  "kg/s": "KiloGM-PER-SEC",
  V: "V",
  mV: "MilliV",
  "V/m": "V-PER-M",
  "V/K": "V-PER-K",
  A: "A",
  mA: "MilliA",
  "A/m": "A-PER-M",
  "A/m²": "A-PER-M2",
  "Am²": "A-M2",
  Ω: "OHM",
  Ωm: "OHM-M",
  S: "S",
  "S/m": "S-PER-M",
  F: "FARAD",
  H: "H",
  T: "T",
  Wb: "WB",
  C: "C",
  Cm: "C-M",
  "C/m²": "C-PER-M2",
  "C/m³": "C-PER-M3",
  Hz: "HZ",
  "1/s": "PER-SEC",
  W: "W",
  kW: "KiloW",
  "W/m²": "W-PER-M2",
  "W/mK": "W-PER-M-K",
  J: "J",
  Js: "J-SEC",
  "J/K": "J-PER-K",
  "J/mol": "J-PER-MOL",
  mol: "MOL",
  Wh: "W-HR",
  kWh: "KiloW-HR",
  MWh: "MegaW-HR",
  VAh: "V-A-HR",
  kVAh: "KiloV-A-HR",
  VARh: "V-A_Reactive-HR",
  kVARh: "KiloV-A_Reactive-HR",
  N: "N",
  "N/m": "N-PER-M",
  Nm: "N-M",
  "m²/N": "M2-PER-N",
};

/** "°C" ergibt "unit:DEG_C" (Praefix im TD-Kontext), unbekannte Einheiten nichts. */
export function qudtUnit(knxUnit: string | undefined): string | undefined {
  if (knxUnit === undefined) return undefined;
  const code = KNX_TO_QUDT[knxUnit.trim()];
  return code === undefined ? undefined : `unit:${code}`;
}
